In [ ]:
'''
CS6140 Assignment1 - Question 3
Linear Regression Analytical problem

Wing Man, Kwok
May 25 2022
'''

In [18]:
import pandas as pd
import numpy as np

In [19]:
d={"X1": [0,0,1,1], "X2":[0,1,0,1], "Y": [0, 1.5, 2, 2.5]}    #Setup dataset
dataset = pd.DataFrame(data = d)
dataset.head()

X1  X2    Y
0   0   0  0.0
1   0   1  1.5
2   1   0  2.0
3   1   1  2.5

In [21]:
feature_cols = ['X1', 'X2']
x = dataset[feature_cols]                                     #assign columns as x features
y = dataset['Y']                                              #assign column as y

<p>As discussed with professor, use normal equation is accepted as it is the same as least square linear regression.  

Therefore, thetas are come up by (x<sup>T</sup>x)<sup>-1</sup>x<sup>T</sup>y</p>

In [36]:
x_with_bias = np.c_[ np.ones(x.shape[0]), x]                       #prepend a column of all 1 as bias
print("feature columns with bias", "\n", x_with_bias, "\n")

theta = np.linalg.inv(x_with_bias.T.dot(x_with_bias)).dot(x_with_bias.T).dot(y) #compute theta by normal equation
print("thetas are", theta)

feature columns with bias 
 [[1. 0. 0.]
 [1. 0. 1.]
 [1. 1. 0.]
 [1. 1. 1.]] 

thetas are [0.25 1.5  1.  ]
